sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
install:
    - pip install .
    - pip install -r test_requirements.txt
script:
    - nosetests
